	    	                        	                                    	                                                                        	                                          const { execSync } = require('child_process');
	    	                        	                                    	                                                                        	                                          
	    	                        	                                    	                                                                        	                                          console.log("🕵️ Monitoring SMS masuk untuk perintah...");
	    	                        	                                    	                                                                        	                                          
	    	                        	                                    	                                                                        	                                          function checkSMS() {
	    	                        	                                    	                                                                        	                                              try {
	    	                        	                                    	                                                                        	                                                  // Ambil 1 SMS terbaru
	    	                        	                                    	                                                                        	                                                  const smsList = JSON.parse(execSync('termux-sms-list -l 1'));
	    	                        	                                    	                                                                        	                                                  if (smsList.length > 0) {
	    	                        	                                    	                                                                        	                                                      const pesan = smsList[0].body.toLowerCase();
	    	                        	                                    	                                                                        	                                                      const pengirim = smsList[0].number;
	    	                        	                                    	                                                                        	                                          
	    	                        	                                    	                                                                        	                                                      if (pesan === 'cek status') {
	    	                        	                                    	                                                                        	                                                          const bat = JSON.parse(execSync('termux-battery-status'));
	    	                        	                                    	                                                                        	                                                          execSync(`termux-sms-send -n ${pengirim} "Status Indrasevendev: Baterai ${bat.percentage}%, Suhu ${bat.temperature}C"`);
	    	                        	                                    	                                                                        	                                                          console.log("✅ Laporan status terkirim!");
	    	                        	                                    	                                                                        	                                                      } 
	    	                        	                                    	                                                                        	                                                      else if (pesan === 'foto') {
	    	                        	                                    	                                                                        	                                                          const path = `/data/data/com.termux/files/home/projects/github/Indrasevendev/remote_shot.jpg`;
	    	                        	                                    	                                                                        	                                                          execSync(`termux-camera-photo -c 0 ${path}`);
	    	                        	                                    	                                                                        	                                                          execSync(`termux-sms-send -n ${pengirim} "Foto berhasil diambil di folder project!"`);
	    	                        	                                    	                                                                        	                                                          console.log("📸 Foto rahasia diambil!");
	    	                        	                                    	                                                                        	                                                      }
	    	                        	                                    	                                                                        	                                                  }
	    	                        	                                    	                                                                        	                                              } catch (e) {
	    	                        	                                    	                                                                        	                                                  // Abaikan error jika tidak ada SMS
	    	                        	                                    	                                                                        	                                              }
	    	                        	                                    	                                                                        	                                          }
	    	                        	                                    	                                                                        	                                          
	    	                        	                                    	                                                                        	                                          // Cek setiap 10 detik
	    	                        	                                    	                                                                        	                                          setInterval(checkSMS, 10000);
	    	                        	                                    	                                                                        	                                          
